// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

namespace SpaBingo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190724194929_RowModel")]
    partial class RowModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Entities.BingoNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPlayed");

                    b.Property<string>("NumValue");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("BingoNumbers");
                });

            modelBuilder.Entity("WebApi.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("WebApi.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("B");

                    b.Property<int>("CardID");

                    b.Property<string>("G");

                    b.Property<string>("I");

                    b.Property<string>("N");

                    b.Property<string>("O");

                    b.HasKey("Id");

                    b.HasIndex("CardID");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("WebApi.Entities.Row", b =>
                {
                    b.HasOne("WebApi.Entities.Card")
                        .WithMany("Rows")
                        .HasForeignKey("CardID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
